title: Bradley Otieno | Infrastructure & Cloud Engineer
logo: /assets/img/logo.png
description: High-Availability Enterprise Systems and Cloud Architecture Portfolio.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
